# Numpy Assignment:

In [1]:
import numpy as np

1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [2]:
arr=np.arange(6)

In [3]:
print(arr)
type(arr)

[0 1 2 3 4 5]


numpy.ndarray

2. Given a NumPy array 'arr', check if its data type is float64.
     arr = np.array([1.5, 2.6, 3.7])


In [4]:
arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.


In [5]:
arr = np.array([1+2j, 3+4j, 5+6j])
arr.dtype

dtype('complex128')

4. Convert an existing NumPy array 'arr' of integers to float32 data type.


In [6]:
arr=np.array([13,46,76,34,23])
float_num=arr.astype(float)
float_num

array([13., 46., 76., 34., 23.])

5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


In [7]:
float64_arr=np.array(1.155454557)

In [8]:
float32_arr=float64_arr.astype(np.float32)

In [9]:
float32_arr

array(1.1554545, dtype=float32)

6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data 
type.

In [10]:
def array_attributes(n):
    b=np.array(n)
    shape=b.shape
    size=b.size
    dtype=b.dtype
    return shape,size,dtype


In [11]:
array_attributes([[1,5,69,2],[2,6,9,7]])

((2, 4), 8, dtype('int32'))

7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


In [12]:
def array_dimension(arr):
    arr1=np.array(arr)
    return arr1.ndim

In [13]:
array_dimension([[[1,2,3],[5,6,9],[2,5,8]]])

3

8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
size in bytes.

In [14]:
def  item_size_info(arr):
    ar=np.array(arr)
    return ar.itemsize,ar.nbytes 

In [15]:
item_size_info([[1,3,6],[5,9,3]])

(4, 24)

9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.


In [16]:
def array_strides(n):
    arr=np.array(n)
    return arr.strides

In [17]:
array_strides([[1,3,6],[5,9,3]])

(12, 4)

10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
and strides of the array.

In [18]:
def shape_stride_relationship(n):
    arr=np.array(n)
    return arr.shape,arr.strides

In [19]:
shape_stride_relationship([[1,3,6],[5,9,3]])

((2, 3), (12, 4))

11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
zeros with `n` elements.

In [20]:
def create_zeros_array(n):
    arr=np.zeros(n)
    return arr

In [21]:
create_zeros_array(5)

array([0., 0., 0., 0., 0.])

12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
NumPy array filled with ones of size `rows x cols`.

In [22]:
def create_ones_matrix(rows,cols):
    arr=np.ones(rows)
    arr1=np.ones(cols)
    return arr, arr1

In [23]:
create_ones_matrix((5),(6))

(array([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1., 1.]))

13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
`step`.

In [24]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

In [25]:
generate_range_array(1,10,3)

array([1, 4, 7])

14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
(inclusive).

In [26]:
def generate_linear_space(start,stop,num=20):
    return np.linspace(start,stop,num=20)

In [27]:
generate_linear_space(1.5,5.6)

array([1.5       , 1.71578947, 1.93157895, 2.14736842, 2.36315789,
       2.57894737, 2.79473684, 3.01052632, 3.22631579, 3.44210526,
       3.65789474, 3.87368421, 4.08947368, 4.30526316, 4.52105263,
       4.73684211, 4.95263158, 5.16842105, 5.38421053, 5.6       ])

15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
identity matrix of size `n x n` using `numpy.eye`.

In [28]:
def create_identity_matrix(n):
    return np.eye(n)

In [29]:
create_identity_matrix(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

16. Write a function that takes a Python list and converts it into a NumPy array.

In [30]:
def list_To_numpy(l):
    return np.array(l)

In [31]:
list_To_numpy([1,5,6,8,4])

array([1, 5, 6, 8, 4])

17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
same data.

In [32]:
arr=np.array([1,2,3,4,5,6])
arr1=arr.view().reshape(2,3)
arr1[1:3]
print(arr)
print(arr1,"New data")

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]] New data


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.


In [33]:
def numpy_conc(a,b,axis=0):
    return np.concatenate((a,b),axis=axis)

In [34]:
numpy_conc([1,2,3],[4,5,6])

array([1, 2, 3, 4, 5, 6])

19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

concatenate`.

In [35]:
arr=np.array([1,2,3,6])
arr1=np.array([7,8,9])
arr2=np.concatenate((arr,arr1))
arr2

array([1, 2, 3, 6, 7, 8, 9])

20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [36]:
def ver_stack(n):
    return np.vstack(n)

In [37]:
ver_stack([1,2,3,6,84,5,7])

array([[ 1],
       [ 2],
       [ 3],
       [ 6],
       [84],
       [ 5],
       [ 7]])

21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
with a given step size.

In [38]:
def func(a,b,c=2):
    return np.arange(a,b+1,c)

In [39]:
func(2,10)

array([ 2,  4,  6,  8, 10])

22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
(inclusive).

In [40]:
def eq_spc_val():
    return np.linspace(0,1,10)
eq_spc_val()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
1000 (inclusive).

In [41]:
def logarithmically_spaced(start,stop):
    return np.logspace(start,stop,5)


In [42]:
logarithmically_spaced(1,1000)

C:\Users\shada\anaconda3\Lib\site-packages\numpy\core\function_base.py:284: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
are random integers between 1 and 100.

In [43]:
import pandas as pd

n=np.random.randint(1,100,size=(5,3))
df=pd.DataFrame(n,columns=['Column1', 'Column2', 'Column3'])
df

Column1  Column2  Column3
0       37       64        6
1       96       77       99
2       51       34       49
3       25        1       77
4       36       17       17

25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
with zeros. Use NumPy operations within the Pandas DataFrame.

26. Access the 3rd element from the given NumPy array.

In [44]:
arr = np.array([10, 20, 30, 40, 50])
arr[3:4]

array([40])

27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [45]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1,2]

6

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [46]:
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr>5]

array([ 8, 10,  7])

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[1:5]

array([2, 3, 4, 5])

30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array

In [48]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[:2,1:3]

array([[2, 3],
       [5, 6]])

31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
provided in another array.

In [49]:
def arr_ind(a,inc):
    a=np.array([[5, 10, 15],
                [20, 25, 30],
                [35, 40, 45],
                [50, 55, 60]])
    inc = np.array([[0, 1],  
                    [3, 2],
                    [2, 0],
                    [1, 2]])
    print(a[inc])
arr_ind()

TypeError: arr_ind() missing 2 required positional arguments: 'a' and 'inc'

32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
boolean indexing.

In [ ]:
def greater_than(n,threshold):
    b=np.array(n)
    return b[b>threshold]
greater_than([1,3,69,8,5,1,4,5,6,65,11],7)

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
separate arrays for each dimension.

In [ ]:
def extract_elements_3d(arr_3d, indices_x, indices_y, indices_z):
    return arr_3d[indices_x, indices_y, indices_z]
arr_3d = np.array([[[ 11,  21,  13],
                    [ 4,  15,  6],
                    [ 17,  8,  19]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 26],
                    [21, 25, 24],
                    [25, 23, 29]]])

indices_x = np.array([0, 1, 2])
indices_y = np.array([2, 0, 1])
indices_z = np.array([2, 1, 0])

extracted_elements = extract_elements_3d(arr_3d, indices_x, indices_y, indices_z)

print(extracted_elements)

34. Write a NumPy function that returns elements from an array where both two conditions are satisfied 
using boolean indexing.

In [ ]:
def filter_conditions(arr, cond_1, cond_2):
    return arr[(cond_1(arr)) & (cond_2(arr))]
arr = np.array([3, 8, 1, 12, 5, 18, 7])
cond_1 = lambda x: x > 5
cond_2 = lambda x: x < 15

filtered_elements = filter_conditions(arr, cond_1, cond_2)

print(filtered_elements) 


35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
in separate arrays.

In [ ]:
def extract_2d(n,row,col):
    return n[row,col]
n=np.array([[10, 20, 30],
            [40, 50, 60],
            [70, 80, 90]])
row=np.array([1,0,1])
col=np.array([1,0,2])
new=extract_2d(n,row,col)
print(new)

36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
arr3=np.arange(1,10).reshape(3,3)
print(arr3)
arr3+5

37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 3). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting.

In [ ]:
arr1=np.arange(1,4).reshape(1,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print("----------")
print(arr2)
print("----------")
arr3=arr2*arr1
print(arr3)

38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
NumPy broadcasting.

In [ ]:
arr1=np.arange(1,5).reshape(1,4)
arr2=np.arange(1,13).reshape(3,4)
arr3=arr1+arr2
print(arr1)
print("----------")
print(arr2)
print("----------")
arr3=arr2+arr1
print(arr3)

39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
broadcasting.

In [ ]:
arr1=np.arange(1,4).reshape(3,1)
arr2=np.arange(1,4).reshape(1,3)
arr3=arr1+arr2
print(arr1)
print("----------")
print(arr2)
print("----------")
arr3=arr1+arr2
print(arr3)

40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

In [ ]:
arr1=np.arange(1,7).reshape(2,3)
arr2=np.arange(1,5).reshape(2,2)
arr_new=arr2.reshape(2,2,1)
arr3=arr_new*arr1
print(arr3)

41. Calculate column wise mean for the given array:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean=np.mean(arr,axis=0)
column_mean

42. Find maximum value in each row of the given array:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_val=np.max(arr,axis=1)
max_val

43. For the given array, find indices of maximum value in each column.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
ind_max=np.argmax(arr,axis=0)
ind_max

44. For the given array, apply custom function to calculate moving sum along rows.

In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
cal_sum=np.sum(arr,axis=0)
cal_sum

array([5, 7, 9])

45. In the given array, check if all elements in each column are even.

In [51]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
check_even=np.all(arr%2==0,axis=1)
check_even

array([ True, False])

46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.

In [52]:
original_array = np.array([1, 2, 3, 4, 5, 6]).reshape(2,3)
original_array

array([[1, 2, 3],
       [4, 5, 6]])

47. Create a function that takes a matrix as input and returns the flattened array.

In [53]:
def flattened_array(input_matrix):
    return input_matrix.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
new=flattened_array(input_matrix)
print(new)



[1 2 3 4 5 6]


48. Write a function that concatenates two given arrays along a specified axis.

In [54]:
def conc_two_arr(array1,array2,axis=0):
    return np.concatenate((array1,array2),axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
axis0=conc_two_arr(array1,array2,axis=0)
print("Axis_0",axis0)
axis1=conc_two_arr(array1,array2,axis=1)
print("Axis_1",axis1)

Axis_0 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Axis_1 [[1 2 5 6]
 [3 4 7 8]]


49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [55]:
def Sub_arr(original_array):
    return np.split(original_array,3)
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new=Sub_arr(original_array)
for i in new:
    print(i)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


50. Write a function that inserts and then deletes elements from a given array at specified indices.

In [56]:
def func(original_array,indices_to_insert,values_to_insert,indices_to_delete):
    return np.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

SyntaxError: invalid syntax (1199215084.py, line 2)

51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [57]:
arr1=np.random.randn(10)
arr2=np.arange(1,11)
element_wise_addition=arr1+arr2
print(element_wise_addition)

[ 1.30355642  1.83974395  3.34824815  2.98113222  5.9640554   6.95031387
  6.03294844  8.11373694  8.19895024 10.41622277]


52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [58]:
arr1=np.arange(11,1,-1)
arr2=np.arange(1,11)
sub=arr1-arr2
print(sub)

[10  8  6  4  2  0 -2 -4 -6 -8]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [59]:
arr1=np.random.rand(5)
arr2=np.arange(1,6)
mul=arr1*arr2
print(mul)

[0.93411552 0.75886537 0.66025991 2.14030355 0.65155093]


54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [60]:
arr1=np.arange(2,12,2)
arr2=np.arange(1,6)
div_arrs=arr1/arr2
print(div_arrs)

[2. 2. 2. 2. 2.]


55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [61]:
arr1=np.arange(1,6)
arr2=np.arange(5,0,-1)
expon_arr=np.power(arr1,arr2)
print(expon_arr)

[ 1 16 27 16  5]


56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [62]:
def count_sub_str(arr,sub_str):
    return np.char.count(arr,sub_str)
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
sub_str='numpy'
occur=count_sub_str(arr,sub_str)
print(occur)



[0 0 0 1 0]


57. Write a function that extracts uppercase characters from a NumPy array of strings.

In [63]:
def extract_upp(arr):
    upper_case_char=np.array([''.join([char for char in string if char.isupper()]) for string in arr])
    return upper_case_char
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppr=extract_upp(arr)
print(uppr)

['H' 'W' 'OAI' 'GPT']


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [64]:
def replace_subtr(arr,new):
    return np.char.replace(arr,new)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_srt=replace_subtr(arr,'apples','grapes')
print(new_srt)


TypeError: replace_subtr() takes 2 positional arguments but 3 were given

59. Write a function that concatenates strings in a NumPy array element-wise.

In [65]:
def conc_str(arr1,arr2):
    return np.char.add(arr1,arr2)
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
new=conc_str(arr1,arr2)
print(new)

['HelloOpen' 'WorldAI']


60. Write a function that finds the length of the longest string in a NumPy array.

In [66]:
def long_str(arr):
    leng=np.vectorize(len)(arr)
    longest_str_ind = np.argmax(leng)
    return arr[longest_str_ind]

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_str=long_str(arr)
print(longest_str)


pineapple


61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

In [67]:
dataset=np.random.randint(1,1001,size=100)
mean=np.mean(dataset)
median=np.median(dataset)
variance=np.var(dataset)
standard_deviation=np.std(dataset)
print(dataset)
print('mean','=',mean,'median','=',median,'variance','=','standard deviation','=',standard_deviation)

[533 600 154 248 905  46 279 945 790 610 694 540 100 999 280 224 651 529
 866 171 296 757 568 101 713 704 585 221 403 810  32 675 306 724 662 729
 210 775 184 237 666 232 815 238 207 685 169 962 453 627 531 480 655 213
 773 989 889 890 711 517 802 559 535 663 522 915 421 776 868 680  59 128
 830 276 138 275 325 931 312 981 442   3 299 247 709 869 318 878 393 383
 299 994 966 113 821 217 882 627 867 696]
mean = 535.77 median = 563.5 variance = standard deviation = 283.1610444605684


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [68]:
arr=np.random.randint(1,101,50)
perc=np.percentile(arr,[25,75])
print(perc)


[19.75 75.  ]


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [69]:
arr1=np.array([12,26,38,41,53])
arr2=np.array([66,47,68,19,10])
cor_coef=np.corrcoef(arr1,arr2)
print(cor_coef)

[[ 1.         -0.74266059]
 [-0.74266059  1.        ]]


64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.


In [70]:
mat1=np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])
mat2=np.array([[2,9,6],
              [6,9,7],
              [9,7,8]])
mat_mult=np.dot(mat1,mat2)
print(mat_mult)

[[ 41  48  44]
 [ 92 123 107]
 [143 198 170]]


65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
percentiles along with the first and third quartiles.

In [71]:
arr=np.random.randint(10,1000,size=50)

percentile_10 = np.percentile(arr, 10)
median = np.percentile(arr, 50)
percentile_90 = np.percentile(arr, 90)

first_quartile = np.percentile(arr, 25)
third_quartile = np.percentile(arr, 75)
print(f"Array: {arr}")
print(f"10th Percentile: {percentile_10}")
print(f"Median (50th Percentile): {median}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile (25th Percentile): {first_quartile}")
print("Third Quartile (75th Percentile) {}".format(third_quartile))
# print(f"Third Quartile (75th Percentile): {third_quartile}")

Array: [598 696  66 352 318 593 402 496 640 841 187 932  26 998 566 288 652 281
 589 397 701 855 442 790 673 475 146 474 267 821 675 590 484 653  60 173
 913 166 664 414 323 976 776 272 358 367 970 400 791 770]
10th Percentile: 172.3
Median (50th Percentile): 531.0
90th Percentile: 860.8000000000001
First Quartile (25th Percentile): 330.25
Third Quartile (75th Percentile) 699.75


66. Create a NumPy array of integers and find the index of a specific element.


In [72]:
arr=np.array([ 11,7,8,9,10,54,15,16,1,17,2,11,12,13,23,46,51,6,18])
ind_arr=np.where(arr==7)
ind_arr

(array([1], dtype=int64),)

67. Generate a random NumPy array and sort it in ascending order.

In [73]:
arr=np.random.randint(1,51,size=50)
print("un_sorted",arr)
sorted_arr=np.sort(arr)
print("sorted_array",sorted_arr)

un_sorted [36 23 21 34 43 50 41  2 39  2 15  8 14 46 18 42 42 18 25 15 43 27 49 15
 11 28 34  8 32  8 41 24 20 34 34 48 42 34 34 48 22  6 47 38  8 24 38 28
 38  4]
sorted_array [ 2  2  4  6  8  8  8  8 11 14 15 15 15 18 18 20 21 22 23 24 24 25 27 28
 28 32 34 34 34 34 34 34 36 38 38 38 39 41 41 42 42 42 43 43 46 47 48 48
 49 50]


68. Filter elements >20  in the given NumPy array.

In [74]:
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

69. Filter elements which are divisible by 3 from a given NumPy array.


In [75]:
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.


In [76]:
arr = np.array([10, 20, 30, 40, 50])
arr[(arr>20) & (arr<40)]

array([30])

71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.


In [77]:
arr = np.array([1, 2, 3])
check_byt=arr.dtype.byteorder
check_byt

'='

72. For the given NumPy array, perform byte swapping in place using `byteswap()`.


In [78]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)

array([16777216, 33554432, 50331648])

73. For the given NumPy array, swap its byte order without modifying the original array using 
`newbyteorder()`.

In [79]:
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr=arr.byteswap().newbyteorder()
swapped_arr

array([1, 2, 3])

74. For the given NumPy array and swap its byte order conditionally based on system endianness using 
`newbyteorder()`.

In [80]:
import sys

In [81]:
arr = np.array([1, 2, 3], dtype=np.int32)
system_endianness = sys.byteorder

if system_endianness == 'little':
    swapped_arr = arr.newbyteorder('>')
else:
    swapped_arr = arr.newbyteorder('<')

print("System endianness:", system_endianness)
print("Original array:", arr)
print("Conditionally byte-swapped array:", swapped_arr)

System endianness: little
Original array: [1 2 3]
Conditionally byte-swapped array: [16777216 33554432 50331648]


75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
attribute `byteorder`.

In [82]:
arr = np.array([1, 2, 3], dtype=np.int32)

system_endianness = sys.byteorder

array_byteorder = arr.dtype.byteorder

if (system_endianness == 'little' and array_byteorder == '>') or (system_endianness == 'big' and array_byteorder == '<'):
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is NOT necessary.")

print(f"System endianness: {system_endianness}")
print(f"Array byte order: {array_byteorder}")

Byte swapping is NOT necessary.
System endianness: little
Array byte order: =


76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [83]:
arr1=np.arange(1,11)
print('original_arr',arr1)
copy_arr=arr1.copy()
copy_arr[8]=11
print('copy_arr',copy_arr)

original_arr [ 1  2  3  4  5  6  7  8  9 10]
copy_arr [ 1  2  3  4  5  6  7  8 11 10]


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [84]:
matrix = np.random.randint(1, 11, (3, 3))

view_slice = matrix[:2, :2]

print("Original matrix:\n", matrix)
print("View slice:\n", view_slice)

view_slice[0, 0] = 99

print("\nModified view slice:\n", view_slice)
print("Original matrix after modifying the slice:\n", matrix)

Original matrix:
 [[ 3  9  9]
 [10  1  7]
 [ 8  6  3]]
View slice:
 [[ 3  9]
 [10  1]]

Modified view slice:
 [[99  9]
 [10  1]]
Original matrix after modifying the slice:
 [[99  9  9]
 [10  1  7]
 [ 8  6  3]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [108]:
array_a=np.random.randint(1,12,(4,3))
view_b=array_a[:2,:2]
broad=view_b+5
print("arra_a\n",array_a)
print('broad_cst_5\n',broad)
print('view_b\n',view_b)

arra_a
 [[ 9  7  4]
 [ 2  6  9]
 [ 9 11  7]
 [11  8  7]]
broad_cst_5
 [[14 12]
 [ 7 11]]
view_b
 [[9 7]
 [2 6]]


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
reflects changes in the original `orig_array`.

In [110]:
orig_array = np.arange(1, 9).reshape(2, 4)
print(orig_array)
reshaped_view = orig_array.reshape(4, 2)

reshaped_view[2, 1] = 100

print("Original Array (orig_array):")
print(orig_array)

print("\nReshaped View (reshaped_view):")
print(reshaped_view)

[[1 2 3 4]
 [5 6 7 8]]
Original Array (orig_array):
[[  1   2   3   4]
 [  5 100   7   8]]

Reshaped View (reshaped_view):
[[  1   2]
 [  3   4]
 [  5 100]
 [  7   8]]


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [119]:
data=np.arange(1,13).reshape(3,4)
print('original data\n',data)
data_copy=data.copy()
print('copy_data\n',data_copy)
greater_5=data_copy[data_copy>5]
modify=greater_5[3]=12
print('modify_data\n',modify)

original data
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
copy_data
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
modify_data
 12


81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
operations between them.

In [126]:
A=np.matrix([[10, 12, 23], [14, 5, 16], [27, 8, 19]])
B=np.matrix([[11, 32, 31], [4, 15, 26], [17, 18, 49]])
add=A+B
print(A)
print("addition\n",add)
sub=A-B
print(B)
print("subtraction\n",sub)

[[10 12 23]
 [14  5 16]
 [27  8 19]]
addition
 [[21 44 54]
 [18 20 42]
 [44 26 68]]
[[11 32 31]
 [ 4 15 26]
 [17 18 49]]
subtraction
 [[ -1 -20  -8]
 [ 10 -10 -10]
 [ 10 -10 -30]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [137]:
C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))
mul=np.dot(C,D)
print(mul)

[[27 39 30 28]
 [17 23 19 16]
 [47 71 52 52]]


83. Create a matrix `E` and find its transpose.

In [149]:
E = np.random.randint(1, 10, (3,3))
print(E)
tran=np.transpose(E)
print("Transpose\n",tran)

[[8 9 9]
 [2 6 4]
 [5 1 7]]
Transpose
 [[8 2 5]
 [9 6 1]
 [9 4 7]]


84. Generate a square matrix `F` and compute its determinant.

In [154]:
F=np.random.randint(1,36,(4,4))
determinant = np.linalg.det(F)
print(determinant)

-226456.00000000012


85. Create a square matrix `G` and find its inverse.

In [155]:
G = np.array([[1, 2], [3, 4]])
print(G)
G_inv = np.linalg.inv(G)
print(G_inv)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
